FROM node:22-alpine

WORKDIR /app

# Copy package and Prisma
COPY server/package*.json ./
COPY server/prisma ./prisma

# Install deps
RUN npm install

# Copy source and tsconfig
COPY server/src ./src
COPY server/prisma.config.ts ./prisma.config.ts
COPY server/tsconfig*.json ./

# Generate Prisma Client
RUN npx prisma generate

# Build TypeScript
RUN npm run build

# Push Prisma schema to DB then start app
CMD ["sh", "-c", "npx prisma db push && node dist/server.js"]
