name: Build and Push Docker Images

on:
  push:
    branches:
      - main   # change to your branch name if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vevit-backend:latest
            ghcr.io/${{ github.repository_owner }}/vevit-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vevit-frontend:latest
            ghcr.io/${{ github.repository_owner }}/vevit-frontend:${{ github.sha }}
